//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class edumaticEntities2 : DbContext
    {
        public edumaticEntities2()
            : base("name=edumaticEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<distractor> distractor { get; set; }
        public virtual DbSet<edumodule> edumodule { get; set; }
        public virtual DbSet<edumodule_gamecontext> edumodule_gamecontext { get; set; }
        public virtual DbSet<enum_diff_level> enum_diff_level { get; set; }
        public virtual DbSet<enum_test_type> enum_test_type { get; set; }
        public virtual DbSet<enum_user_role> enum_user_role { get; set; }
        public virtual DbSet<enum_user_type> enum_user_type { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_distractor> user_distractor { get; set; }
        public virtual DbSet<user_edumodule> user_edumodule { get; set; }
    }
}
