//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class edumodule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public edumodule()
        {
            this.user_edumodule = new HashSet<user_edumodule>();
        }
    
        public int id { get; set; }
        public Nullable<short> id_group { get; set; }
        public string difficulty { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string example { get; set; }
        public string test_type { get; set; }
        public string test_task { get; set; }
        public string test_answer { get; set; }
    
        public virtual enum_diff_levels enum_diff_levels { get; set; }
        public virtual edumodule_gamecontext edumodule_gamecontext { get; set; }
        public virtual enum_test_types enum_test_types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_edumodule> user_edumodule { get; set; }
    }
}
