//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("edumaticModel", "user_distractor_distractor_id_fkey", "distractor", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduApi.distractor), "user_distractor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduApi.user_distractor), true)]
[assembly: EdmRelationshipAttribute("edumaticModel", "edumodule_difficulty_fkey", "enum_diff_levels", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduApi.enum_diff_levels), "edumodule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduApi.edumodule), true)]
[assembly: EdmRelationshipAttribute("edumaticModel", "edumodule_gamecontext_edumodule_id_fkey", "edumodule", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduApi.edumodule), "edumodule_gamecontext", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EduApi.edumodule_gamecontext), true)]
[assembly: EdmRelationshipAttribute("edumaticModel", "edumodule_test_type_fkey", "enum_test_types", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(EduApi.enum_test_types), "edumodule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduApi.edumodule), true)]
[assembly: EdmRelationshipAttribute("edumaticModel", "user_edumodule_edumodule_id_fkey", "edumodule", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduApi.edumodule), "user_edumodule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduApi.user_edumodule), true)]
[assembly: EdmRelationshipAttribute("edumaticModel", "user_distractor_user_id_fkey", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduApi.user), "user_distractor", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduApi.user_distractor), true)]
[assembly: EdmRelationshipAttribute("edumaticModel", "user_edumodule_user_id_fkey", "user", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(EduApi.user), "user_edumodule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(EduApi.user_edumodule), true)]

#endregion

namespace EduApi
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class edumaticEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new edumaticEntities object using the connection string found in the 'edumaticEntities' section of the application configuration file.
        /// </summary>
        public edumaticEntities() : base("name=edumaticEntities", "edumaticEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new edumaticEntities object.
        /// </summary>
        public edumaticEntities(string connectionString) : base(connectionString, "edumaticEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new edumaticEntities object.
        /// </summary>
        public edumaticEntities(EntityConnection connection) : base(connection, "edumaticEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<distractor> distractor
        {
            get
            {
                if ((_distractor == null))
                {
                    _distractor = base.CreateObjectSet<distractor>("distractor");
                }
                return _distractor;
            }
        }
        private ObjectSet<distractor> _distractor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<edumodule> edumodule
        {
            get
            {
                if ((_edumodule == null))
                {
                    _edumodule = base.CreateObjectSet<edumodule>("edumodule");
                }
                return _edumodule;
            }
        }
        private ObjectSet<edumodule> _edumodule;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<edumodule_gamecontext> edumodule_gamecontext
        {
            get
            {
                if ((_edumodule_gamecontext == null))
                {
                    _edumodule_gamecontext = base.CreateObjectSet<edumodule_gamecontext>("edumodule_gamecontext");
                }
                return _edumodule_gamecontext;
            }
        }
        private ObjectSet<edumodule_gamecontext> _edumodule_gamecontext;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<enum_diff_levels> enum_diff_levels
        {
            get
            {
                if ((_enum_diff_levels == null))
                {
                    _enum_diff_levels = base.CreateObjectSet<enum_diff_levels>("enum_diff_levels");
                }
                return _enum_diff_levels;
            }
        }
        private ObjectSet<enum_diff_levels> _enum_diff_levels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<enum_test_types> enum_test_types
        {
            get
            {
                if ((_enum_test_types == null))
                {
                    _enum_test_types = base.CreateObjectSet<enum_test_types>("enum_test_types");
                }
                return _enum_test_types;
            }
        }
        private ObjectSet<enum_test_types> _enum_test_types;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user> user
        {
            get
            {
                if ((_user == null))
                {
                    _user = base.CreateObjectSet<user>("user");
                }
                return _user;
            }
        }
        private ObjectSet<user> _user;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_distractor> user_distractor
        {
            get
            {
                if ((_user_distractor == null))
                {
                    _user_distractor = base.CreateObjectSet<user_distractor>("user_distractor");
                }
                return _user_distractor;
            }
        }
        private ObjectSet<user_distractor> _user_distractor;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<user_edumodule> user_edumodule
        {
            get
            {
                if ((_user_edumodule == null))
                {
                    _user_edumodule = base.CreateObjectSet<user_edumodule>("user_edumodule");
                }
                return _user_edumodule;
            }
        }
        private ObjectSet<user_edumodule> _user_edumodule;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the distractor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodistractor(distractor distractor)
        {
            base.AddObject("distractor", distractor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the edumodule EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToedumodule(edumodule edumodule)
        {
            base.AddObject("edumodule", edumodule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the edumodule_gamecontext EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToedumodule_gamecontext(edumodule_gamecontext edumodule_gamecontext)
        {
            base.AddObject("edumodule_gamecontext", edumodule_gamecontext);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the enum_diff_levels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToenum_diff_levels(enum_diff_levels enum_diff_levels)
        {
            base.AddObject("enum_diff_levels", enum_diff_levels);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the enum_test_types EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToenum_test_types(enum_test_types enum_test_types)
        {
            base.AddObject("enum_test_types", enum_test_types);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser(user user)
        {
            base.AddObject("user", user);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_distractor EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_distractor(user_distractor user_distractor)
        {
            base.AddObject("user_distractor", user_distractor);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the user_edumodule EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTouser_edumodule(user_edumodule user_edumodule)
        {
            base.AddObject("user_edumodule", user_edumodule);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="distractor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class distractor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new distractor object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="distr_content">Initial value of the distr_content property.</param>
        public static distractor Createdistractor(global::System.Int32 id, global::System.String type, global::System.String distr_content)
        {
            distractor distractor = new distractor();
            distractor.id = id;
            distractor.type = type;
            distractor.distr_content = distr_content;
            return distractor;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, false, "type");
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String distr_content
        {
            get
            {
                return _distr_content;
            }
            set
            {
                Ondistr_contentChanging(value);
                ReportPropertyChanging("distr_content");
                _distr_content = StructuralObject.SetValidValue(value, false, "distr_content");
                ReportPropertyChanged("distr_content");
                Ondistr_contentChanged();
            }
        }
        private global::System.String _distr_content;
        partial void Ondistr_contentChanging(global::System.String value);
        partial void Ondistr_contentChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_distractor_distractor_id_fkey", "user_distractor")]
        public EntityCollection<user_distractor> user_distractor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_distractor>("edumaticModel.user_distractor_distractor_id_fkey", "user_distractor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_distractor>("edumaticModel.user_distractor_distractor_id_fkey", "user_distractor", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="edumodule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class edumodule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new edumodule object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="difficulty">Initial value of the difficulty property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="content">Initial value of the content property.</param>
        public static edumodule Createedumodule(global::System.Int32 id, global::System.String difficulty, global::System.String title, global::System.String content)
        {
            edumodule edumodule = new edumodule();
            edumodule.id = id;
            edumodule.difficulty = difficulty;
            edumodule.title = title;
            edumodule.content = content;
            return edumodule;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> id_group
        {
            get
            {
                return _id_group;
            }
            set
            {
                Onid_groupChanging(value);
                ReportPropertyChanging("id_group");
                _id_group = StructuralObject.SetValidValue(value, "id_group");
                ReportPropertyChanged("id_group");
                Onid_groupChanged();
            }
        }
        private Nullable<global::System.Int16> _id_group;
        partial void Onid_groupChanging(Nullable<global::System.Int16> value);
        partial void Onid_groupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String difficulty
        {
            get
            {
                return _difficulty;
            }
            set
            {
                OndifficultyChanging(value);
                ReportPropertyChanging("difficulty");
                _difficulty = StructuralObject.SetValidValue(value, false, "difficulty");
                ReportPropertyChanged("difficulty");
                OndifficultyChanged();
            }
        }
        private global::System.String _difficulty;
        partial void OndifficultyChanging(global::System.String value);
        partial void OndifficultyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false, "title");
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String content
        {
            get
            {
                return _content;
            }
            set
            {
                OncontentChanging(value);
                ReportPropertyChanging("content");
                _content = StructuralObject.SetValidValue(value, false, "content");
                ReportPropertyChanged("content");
                OncontentChanged();
            }
        }
        private global::System.String _content;
        partial void OncontentChanging(global::System.String value);
        partial void OncontentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String example
        {
            get
            {
                return _example;
            }
            set
            {
                OnexampleChanging(value);
                ReportPropertyChanging("example");
                _example = StructuralObject.SetValidValue(value, true, "example");
                ReportPropertyChanged("example");
                OnexampleChanged();
            }
        }
        private global::System.String _example;
        partial void OnexampleChanging(global::System.String value);
        partial void OnexampleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String test_type
        {
            get
            {
                return _test_type;
            }
            set
            {
                Ontest_typeChanging(value);
                ReportPropertyChanging("test_type");
                _test_type = StructuralObject.SetValidValue(value, true, "test_type");
                ReportPropertyChanged("test_type");
                Ontest_typeChanged();
            }
        }
        private global::System.String _test_type;
        partial void Ontest_typeChanging(global::System.String value);
        partial void Ontest_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String test_task
        {
            get
            {
                return _test_task;
            }
            set
            {
                Ontest_taskChanging(value);
                ReportPropertyChanging("test_task");
                _test_task = StructuralObject.SetValidValue(value, true, "test_task");
                ReportPropertyChanged("test_task");
                Ontest_taskChanged();
            }
        }
        private global::System.String _test_task;
        partial void Ontest_taskChanging(global::System.String value);
        partial void Ontest_taskChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String test_answer
        {
            get
            {
                return _test_answer;
            }
            set
            {
                Ontest_answerChanging(value);
                ReportPropertyChanging("test_answer");
                _test_answer = StructuralObject.SetValidValue(value, true, "test_answer");
                ReportPropertyChanged("test_answer");
                Ontest_answerChanged();
            }
        }
        private global::System.String _test_answer;
        partial void Ontest_answerChanging(global::System.String value);
        partial void Ontest_answerChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "edumodule_difficulty_fkey", "enum_diff_levels")]
        public enum_diff_levels enum_diff_levels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<enum_diff_levels>("edumaticModel.edumodule_difficulty_fkey", "enum_diff_levels").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<enum_diff_levels>("edumaticModel.edumodule_difficulty_fkey", "enum_diff_levels").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<enum_diff_levels> enum_diff_levelsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<enum_diff_levels>("edumaticModel.edumodule_difficulty_fkey", "enum_diff_levels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<enum_diff_levels>("edumaticModel.edumodule_difficulty_fkey", "enum_diff_levels", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "edumodule_gamecontext_edumodule_id_fkey", "edumodule_gamecontext")]
        public edumodule_gamecontext edumodule_gamecontext
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule_gamecontext>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule_gamecontext").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule_gamecontext>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule_gamecontext").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<edumodule_gamecontext> edumodule_gamecontextReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule_gamecontext>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule_gamecontext");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<edumodule_gamecontext>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule_gamecontext", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "edumodule_test_type_fkey", "enum_test_types")]
        public enum_test_types enum_test_types
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<enum_test_types>("edumaticModel.edumodule_test_type_fkey", "enum_test_types").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<enum_test_types>("edumaticModel.edumodule_test_type_fkey", "enum_test_types").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<enum_test_types> enum_test_typesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<enum_test_types>("edumaticModel.edumodule_test_type_fkey", "enum_test_types");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<enum_test_types>("edumaticModel.edumodule_test_type_fkey", "enum_test_types", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_edumodule_edumodule_id_fkey", "user_edumodule")]
        public EntityCollection<user_edumodule> user_edumodule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_edumodule>("edumaticModel.user_edumodule_edumodule_id_fkey", "user_edumodule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_edumodule>("edumaticModel.user_edumodule_edumodule_id_fkey", "user_edumodule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="edumodule_gamecontext")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class edumodule_gamecontext : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new edumodule_gamecontext object.
        /// </summary>
        /// <param name="edumodule_id">Initial value of the edumodule_id property.</param>
        /// <param name="game_score">Initial value of the game_score property.</param>
        public static edumodule_gamecontext Createedumodule_gamecontext(global::System.Int32 edumodule_id, global::System.Int32 game_score)
        {
            edumodule_gamecontext edumodule_gamecontext = new edumodule_gamecontext();
            edumodule_gamecontext.edumodule_id = edumodule_id;
            edumodule_gamecontext.game_score = game_score;
            return edumodule_gamecontext;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 edumodule_id
        {
            get
            {
                return _edumodule_id;
            }
            set
            {
                if (_edumodule_id != value)
                {
                    Onedumodule_idChanging(value);
                    ReportPropertyChanging("edumodule_id");
                    _edumodule_id = StructuralObject.SetValidValue(value, "edumodule_id");
                    ReportPropertyChanged("edumodule_id");
                    Onedumodule_idChanged();
                }
            }
        }
        private global::System.Int32 _edumodule_id;
        partial void Onedumodule_idChanging(global::System.Int32 value);
        partial void Onedumodule_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 game_score
        {
            get
            {
                return _game_score;
            }
            set
            {
                Ongame_scoreChanging(value);
                ReportPropertyChanging("game_score");
                _game_score = StructuralObject.SetValidValue(value, "game_score");
                ReportPropertyChanged("game_score");
                Ongame_scoreChanged();
            }
        }
        private global::System.Int32 _game_score;
        partial void Ongame_scoreChanging(global::System.Int32 value);
        partial void Ongame_scoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String game_content
        {
            get
            {
                return _game_content;
            }
            set
            {
                Ongame_contentChanging(value);
                ReportPropertyChanging("game_content");
                _game_content = StructuralObject.SetValidValue(value, true, "game_content");
                ReportPropertyChanged("game_content");
                Ongame_contentChanged();
            }
        }
        private global::System.String _game_content;
        partial void Ongame_contentChanging(global::System.String value);
        partial void Ongame_contentChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "edumodule_gamecontext_edumodule_id_fkey", "edumodule")]
        public edumodule edumodule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<edumodule> edumoduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<edumodule>("edumaticModel.edumodule_gamecontext_edumodule_id_fkey", "edumodule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="enum_diff_levels")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class enum_diff_levels : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new enum_diff_levels object.
        /// </summary>
        /// <param name="difficulty">Initial value of the difficulty property.</param>
        public static enum_diff_levels Createenum_diff_levels(global::System.String difficulty)
        {
            enum_diff_levels enum_diff_levels = new enum_diff_levels();
            enum_diff_levels.difficulty = difficulty;
            return enum_diff_levels;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String difficulty
        {
            get
            {
                return _difficulty;
            }
            set
            {
                if (_difficulty != value)
                {
                    OndifficultyChanging(value);
                    ReportPropertyChanging("difficulty");
                    _difficulty = StructuralObject.SetValidValue(value, false, "difficulty");
                    ReportPropertyChanged("difficulty");
                    OndifficultyChanged();
                }
            }
        }
        private global::System.String _difficulty;
        partial void OndifficultyChanging(global::System.String value);
        partial void OndifficultyChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "edumodule_difficulty_fkey", "edumodule")]
        public EntityCollection<edumodule> edumodule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<edumodule>("edumaticModel.edumodule_difficulty_fkey", "edumodule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<edumodule>("edumaticModel.edumodule_difficulty_fkey", "edumodule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="enum_test_types")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class enum_test_types : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new enum_test_types object.
        /// </summary>
        /// <param name="type">Initial value of the type property.</param>
        public static enum_test_types Createenum_test_types(global::System.String type)
        {
            enum_test_types enum_test_types = new enum_test_types();
            enum_test_types.type = type;
            return enum_test_types;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                if (_type != value)
                {
                    OntypeChanging(value);
                    ReportPropertyChanging("type");
                    _type = StructuralObject.SetValidValue(value, false, "type");
                    ReportPropertyChanged("type");
                    OntypeChanged();
                }
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "edumodule_test_type_fkey", "edumodule")]
        public EntityCollection<edumodule> edumodule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<edumodule>("edumaticModel.edumodule_test_type_fkey", "edumodule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<edumodule>("edumaticModel.edumodule_test_type_fkey", "edumodule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="user")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static user Createuser(global::System.Int32 id)
        {
            user user = new user();
            user.id = id;
            return user;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true, "login");
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> score
        {
            get
            {
                return _score;
            }
            set
            {
                OnscoreChanging(value);
                ReportPropertyChanging("score");
                _score = StructuralObject.SetValidValue(value, "score");
                ReportPropertyChanged("score");
                OnscoreChanged();
            }
        }
        private Nullable<global::System.Int32> _score;
        partial void OnscoreChanging(Nullable<global::System.Int32> value);
        partial void OnscoreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> is_teacher
        {
            get
            {
                return _is_teacher;
            }
            set
            {
                Onis_teacherChanging(value);
                ReportPropertyChanging("is_teacher");
                _is_teacher = StructuralObject.SetValidValue(value, "is_teacher");
                ReportPropertyChanged("is_teacher");
                Onis_teacherChanged();
            }
        }
        private Nullable<global::System.Boolean> _is_teacher;
        partial void Onis_teacherChanging(Nullable<global::System.Boolean> value);
        partial void Onis_teacherChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_distractor_user_id_fkey", "user_distractor")]
        public EntityCollection<user_distractor> user_distractor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_distractor>("edumaticModel.user_distractor_user_id_fkey", "user_distractor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_distractor>("edumaticModel.user_distractor_user_id_fkey", "user_distractor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_edumodule_user_id_fkey", "user_edumodule")]
        public EntityCollection<user_edumodule> user_edumodule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<user_edumodule>("edumaticModel.user_edumodule_user_id_fkey", "user_edumodule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<user_edumodule>("edumaticModel.user_edumodule_user_id_fkey", "user_edumodule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="user_distractor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_distractor : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_distractor object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="distractor_id">Initial value of the distractor_id property.</param>
        /// <param name="time_last_used">Initial value of the time_last_used property.</param>
        public static user_distractor Createuser_distractor(global::System.Int32 user_id, global::System.Int32 distractor_id, global::System.DateTime time_last_used)
        {
            user_distractor user_distractor = new user_distractor();
            user_distractor.user_id = user_id;
            user_distractor.distractor_id = distractor_id;
            user_distractor.time_last_used = time_last_used;
            return user_distractor;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value, "user_id");
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 distractor_id
        {
            get
            {
                return _distractor_id;
            }
            set
            {
                if (_distractor_id != value)
                {
                    Ondistractor_idChanging(value);
                    ReportPropertyChanging("distractor_id");
                    _distractor_id = StructuralObject.SetValidValue(value, "distractor_id");
                    ReportPropertyChanged("distractor_id");
                    Ondistractor_idChanged();
                }
            }
        }
        private global::System.Int32 _distractor_id;
        partial void Ondistractor_idChanging(global::System.Int32 value);
        partial void Ondistractor_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime time_last_used
        {
            get
            {
                return _time_last_used;
            }
            set
            {
                Ontime_last_usedChanging(value);
                ReportPropertyChanging("time_last_used");
                _time_last_used = StructuralObject.SetValidValue(value, "time_last_used");
                ReportPropertyChanged("time_last_used");
                Ontime_last_usedChanged();
            }
        }
        private global::System.DateTime _time_last_used;
        partial void Ontime_last_usedChanging(global::System.DateTime value);
        partial void Ontime_last_usedChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_distractor_distractor_id_fkey", "distractor")]
        public distractor distractor
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<distractor>("edumaticModel.user_distractor_distractor_id_fkey", "distractor").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<distractor>("edumaticModel.user_distractor_distractor_id_fkey", "distractor").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<distractor> distractorReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<distractor>("edumaticModel.user_distractor_distractor_id_fkey", "distractor");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<distractor>("edumaticModel.user_distractor_distractor_id_fkey", "distractor", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_distractor_user_id_fkey", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("edumaticModel.user_distractor_user_id_fkey", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("edumaticModel.user_distractor_user_id_fkey", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("edumaticModel.user_distractor_user_id_fkey", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("edumaticModel.user_distractor_user_id_fkey", "user", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="edumaticModel", Name="user_edumodule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class user_edumodule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new user_edumodule object.
        /// </summary>
        /// <param name="user_id">Initial value of the user_id property.</param>
        /// <param name="edumodule_id">Initial value of the edumodule_id property.</param>
        /// <param name="result">Initial value of the result property.</param>
        public static user_edumodule Createuser_edumodule(global::System.Int32 user_id, global::System.Int32 edumodule_id, global::System.Boolean result)
        {
            user_edumodule user_edumodule = new user_edumodule();
            user_edumodule.user_id = user_id;
            user_edumodule.edumodule_id = edumodule_id;
            user_edumodule.result = result;
            return user_edumodule;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                if (_user_id != value)
                {
                    Onuser_idChanging(value);
                    ReportPropertyChanging("user_id");
                    _user_id = StructuralObject.SetValidValue(value, "user_id");
                    ReportPropertyChanged("user_id");
                    Onuser_idChanged();
                }
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 edumodule_id
        {
            get
            {
                return _edumodule_id;
            }
            set
            {
                if (_edumodule_id != value)
                {
                    Onedumodule_idChanging(value);
                    ReportPropertyChanging("edumodule_id");
                    _edumodule_id = StructuralObject.SetValidValue(value, "edumodule_id");
                    ReportPropertyChanged("edumodule_id");
                    Onedumodule_idChanged();
                }
            }
        }
        private global::System.Int32 _edumodule_id;
        partial void Onedumodule_idChanging(global::System.Int32 value);
        partial void Onedumodule_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean result
        {
            get
            {
                return _result;
            }
            set
            {
                OnresultChanging(value);
                ReportPropertyChanging("result");
                _result = StructuralObject.SetValidValue(value, "result");
                ReportPropertyChanged("result");
                OnresultChanged();
            }
        }
        private global::System.Boolean _result;
        partial void OnresultChanging(global::System.Boolean value);
        partial void OnresultChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_edumodule_edumodule_id_fkey", "edumodule")]
        public edumodule edumodule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule>("edumaticModel.user_edumodule_edumodule_id_fkey", "edumodule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule>("edumaticModel.user_edumodule_edumodule_id_fkey", "edumodule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<edumodule> edumoduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<edumodule>("edumaticModel.user_edumodule_edumodule_id_fkey", "edumodule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<edumodule>("edumaticModel.user_edumodule_edumodule_id_fkey", "edumodule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("edumaticModel", "user_edumodule_user_id_fkey", "user")]
        public user user
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("edumaticModel.user_edumodule_user_id_fkey", "user").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("edumaticModel.user_edumodule_user_id_fkey", "user").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<user> userReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<user>("edumaticModel.user_edumodule_user_id_fkey", "user");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<user>("edumaticModel.user_edumodule_user_id_fkey", "user", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
