//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_question
    {
        public int user_id { get; set; }
        public int question_id { get; set; }
        public bool first_result { get; set; }
        public bool result { get; set; }
    
        public virtual test_question test_question { get; set; }
        public virtual user user { get; set; }
    }
}
